### ISSUE TITLE
Code / design review

### ISSUE THREAD

**Issue by Annevd** [Patrickkhr/user-experience-enhanced-website#2]
Tops:
-  Je GET en POST routes staan duidelijk en op goede volgorde geordend.
- Je HTML gaat op volgorde van de pagina en is goed op volgorde van groot naar klein
- Custom properties staan netjes bovenaan je stylesheet
- De algemene styling staat ook netjes bovenaan
- Super nette CSS en je maakt goed gebruik van CSS selectors

**Comment by Patrickkhr** [comment]
Bedankt voor de review en tops!
