### ISSUE TITLE
POST bij GET route zetten

### ISSUE THREAD

**Issue by Annevd** [Patrickkhr/user-experience-enhanced-website#3]
https://github.com/Patrickkhr/user-experience-enhanced-website/blob/6e7ffc3e9740395da3b845d68ed3bfaade79f7b7/server.js#L40-L53

https://github.com/Patrickkhr/user-experience-enhanced-website/blob/6e7ffc3e9740395da3b845d68ed3bfaade79f7b7/server.js#L70-L85

Je GET route en je POST route voor de lessons pagina staan nu niet bij elkaar in je server.js. Je zou kunnen overwegen om deze routes bij elkaar te zetten. Dan zie je namelijk gelijk alle routes die je hebt voor een pagina.

**Comment by Patrickkhr** [comment]
Bedankt voor de tip, ik heb dit gefixed!

https://github.com/Patrickkhr/user-experience-enhanced-website/blob/7a22c2dc447ef497bddfd908aa92c66f6a5b7053/server.js#L70-L98
